In [1]:
## HEALTH CODE INSPECTIONS / YELP

# Are there any words whose presence in a Yelp review 
# might indicate that there is a serious health code violation present at a restaurant?

In [2]:
import csv 
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
from sklearn.linear_model import LinearRegression

In [3]:
## LOADING THE DATA: correctly read input files into pandas DataFrames

# do not use the first column as the index, set header to first row, skip spaces after delimiter
hcvs = pd.read_csv('Health_Code_Violations_Seattle.CSV', index_col = False, header = 0, skipinitialspace = True)

# print head
hcvs.head(5)

# display(hcvs)

C:\Users\jeani\anaconda3\envs\progLab\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Name,Program Identifier,Inspection Date,Description,Address,City,Zip Code,Phone,Longitude,Latitude,...,Inspection Score,Inspection Result,Inspection Closed Business,Violation Type,Violation Description,Violation Points,Business_ID,Inspection_Serial_Num,Violation_Record_ID,Grade
0,"@ THE SHACK, LLC",SHACK COFFEE,08/03/2019,Seating 0-12 - Risk Category III,2920 SW AVALON WAY,Seattle,98126,(206) 938-5665,-122.370913,47.570425,...,5.0,Satisfactory,False,BLUE,4100 - Warewashing facilities properly install...,5,PR0048053,DAAWCFJXT,IVAW6QGCN,1.0
1,"@ THE SHACK, LLC",SHACK COFFEE,10/03/2018,Seating 0-12 - Risk Category III,2920 SW AVALON WAY,Seattle,98126,(206) 938-5665,-122.370913,47.570425,...,10.0,Satisfactory,False,BLUE,"3400 - Wiping cloths properly used, stored, pr...",5,PR0048053,DA1RU2P4A,IVM00AWOV,1.0
2,"@ THE SHACK, LLC",SHACK COFFEE,10/03/2018,Seating 0-12 - Risk Category III,2920 SW AVALON WAY,Seattle,98126,(206) 938-5665,-122.370913,47.570425,...,10.0,Satisfactory,False,BLUE,4100 - Warewashing facilities properly install...,5,PR0048053,DA1RU2P4A,IVTPKYPPP,1.0
3,"@ THE SHACK, LLC",SHACK COFFEE,04/02/2018,Seating 0-12 - Risk Category III,2920 SW AVALON WAY,Seattle,98126,(206) 938-5665,-122.370913,47.570425,...,0.0,Complete,False,NaN,NaN,0,PR0048053,DA34JMIOR,NaN,1.0
4,"@ THE SHACK, LLC",SHACK COFFEE,07/27/2017,Seating 0-12 - Risk Category III,2920 SW AVALON WAY,Seattle,98126,(206) 938-5665,-122.370913,47.570425,...,0.0,Satisfactory,False,NaN,NaN,0,PR0048053,DADNXR5VS,NaN,1.0

In [4]:
# YELP DATA

In [5]:
# read file
buisnessdata = [json.loads(line) for line in open('business.json', 'r')]

# display(buisnessdata)